services:
  - type: web
    name: tech-challenge1-api
    runtime: python
    region: oregon
    plan: free

    buildCommand: |
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --without dev 

    startCommand: uvicorn tech_challenge1.api.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ENVIRONMENT
        sync: false
