services:
  - type: web
    name: tech-challenge1-api
    runtime: python
    region: oregon
    plan: free

    buildCommand: |
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --without dev

    startCommand: uvicorn tech_challenge1.api.main:app --host 0.0.0.0 --port 10000

    envVars:
      - key: SECRET_KEY
      - key: ALGORITHM
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
      - key: DATABASE_URL
      - key: ENVIRONMENT
      - key: DASHBOARD_USER
      - key: DASHBOARD_PASSWORD
